language: python

python:
  - "3.6"

matrix:
  fast_finish: true

install: pip install -U tox-travis
script: tox

notifications:
  email:
    on_success: change
    on_failure: always

script:
  - yarn build-storybook

deploy:
  provider: s3


  # - provider: s3
  #   bucket: "{{cookiecutter.s3_bucket_backend}}"
  #   skip_cleanup: true
  #   local_dir: zappa_output
  #   acl: public_read
  #   region: {{cookiecutter.region}}

  # - provider: s3
  #   bucket: "{{cookiecutter.s3_bucket_backend}}-static"
  #   skip_cleanup: true
  #   local_dir: static
  #   acl: public_read
  #   region: {{cookiecutter.region}}

